service: afscme-serverless
frameworkVersion: "3"

custom:
  affiliations_table: "affiliations"
  leads_table: "leads"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:*:*:table/${self:custom.affiliations_table}
            - arn:aws:dynamodb:*:*:table/${self:custom.affiliations_table}/index/*
            - arn:aws:dynamodb:*:*:table/${self:custom.leads_table}

  environment:
    AFFILIATIONS_TABLE: ${self:custom.affiliations_table}
    LEADS_TABLE: ${self:custom.leads_table}

functions:
  affiliation:
    handler: functions/affiliation.handler
    events:
      - httpApi:
          method: GET
          path: /affiliations
      - httpApi:
          method: GET
          path: /affiliations/{id}
      - httpApi:
          method: POST
          path: /affiliations

  lead:
    handler: functions/leads.handler
    events:
      - httpApi:
          method: GET
          path: /leads/{id}
      - httpApi:
          method: POST
          path: /leads

resources:
  Resources:
    Affiliations:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.affiliations_table}
    Leads:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.leads_table}
