service: afscme-serverless
frameworkVersion: "3"

custom:
  affiliations_table: "affiliations"
  leads_table: "leads"
  posts_table: "posts"
  imageupload_bucket: "afscme-sls-bucket"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - "s3:Put*"
          Resource:
            - arn:aws:dynamodb:*:*:table/${self:custom.affiliations_table}
            - arn:aws:dynamodb:*:*:table/${self:custom.affiliations_table}/index/*
            - arn:aws:dynamodb:*:*:table/${self:custom.leads_table}
            - arn:aws:dynamodb:*:*:table/${self:custom.posts_table}
            - arn:aws:s3:::${self:custom.imageupload_bucket}/*

  environment:
    AFFILIATIONS_TABLE: ${self:custom.affiliations_table}
    LEADS_TABLE: ${self:custom.leads_table}
    POSTS_TABLE: ${self:custom.posts_table}
    IMAGEUPLOAD_BUCKET: ${self:custom.imageupload_bucket}

  httpApi:
    cors: true

functions:
  affiliation:
    handler: functions/affiliation.handler
    events:
      - httpApi:
          method: GET
          path: /affiliations
      - httpApi:
          method: GET
          path: /affiliations/{id}
      - httpApi:
          method: POST
          path: /affiliations

  lead:
    handler: functions/leads.handler
    events:
      - httpApi:
          method: GET
          path: /leads/{id}
      - httpApi:
          method: POST
          path: /leads

  post:
    handler: functions/posts.handler
    events:
      - httpApi:
          method: GET
          path: /posts/{id}
      - httpApi:
          method: POST
          path: /posts

  upload:
    handler: functions/upload.handler
    events:
      - httpApi:
          method: POST
          path: /upload-files

resources:
  Resources:
    Affiliations:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.affiliations_table}

    Leads:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.leads_table}

    Posts:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.posts_table}

    ImageUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.imageupload_bucket}
        AccessControl: PublicRead
